hub/urls.py
from django.urls import path,include
from .views import hubList,hubDetail,ProjectCategory,ProjectLanguage
app_name= 'hub'
urlpatterns = [
  
    #path('kenny',views.index, name='index'),
     path('', hubList.as_view(), name='hublist_view'),
     path('<int:pk>/', hubDetail.as_view(), name='hubdetails-detail'),
     path('category/<str:category>/', ProjectCategory.as_view(), name='Cate'),
     path('Language/<str:lang>/', ProjectLanguage.as_view(), name='Lan'),
     
   
]

movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name= 'hub'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hub/', include('hub.urls', namespace='hub')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hub/models.py
from django.db import models

# Create your models here.
class hub(models.Model):
    language = [
    ('PY', 'Python'),
    ('JS', 'Java Script'),
    ('JV', 'Java'),
    ('KOT', 'Kotlin'),
    ('PHP', 'PHP'),
    ('HT', 'Html'),
    ('R', 'R'),
                ]
    cate = [
    ('W', 'Web App'),
    ('A', 'Android'),
    ('D', 'Desktop App'),
    
            ]
    state= [
    ('RA', 'Recently added'),
    ('MW', 'Most Watched'),
    ('TR', 'Top Rated'),
    
            ]
    
    
    def language_default():
        return {"language": "Python"}

 #contact_info = JSONField("ContactInfo", default=contact_default)
    
    title = models.CharField(max_length = 200)
    description = models.TextField(max_length = 600)
    image = models.ImageField(upload_to ='images')
    category = models.CharField(choices = cate ,max_length = 20)
    status = models.CharField(choices= state,max_length = 200) 
    cast = models.CharField(max_length = 200)
    language = models.CharField(choices= language,max_length = 200, default=language_default) 
    year_production=models.DateField()
    View_counts= models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
class CodeLinks(models.Model):
        link_choice=(
                ('D','Download_link'),
                ('W','Watch_link'),
                
        )
        cod = models.ForeignKey(hub, on_delete=models.CASCADE)
        type = models.CharField(choices=link_choice,max_length = 600)
        link =models.URLField()
        
        def __str__(self):
                return self.type

hub/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from hub.models import hub,CodeLinks

# Create your views here.


class hubDetail(DetailView):
    model = hub
    template_name = "detail.html"
    paginate_by =1
    context_object_name = 'detail'
    
    def get_object(self):
        obj = super(hubDetail,self).get_object()
        obj.View_counts +=1
        obj.save()
        return obj
    
    def get_context_data(self, **kwargs):
        context = super(hubDetail,self).get_context_data(**kwargs)
        context['link'] = CodeLinks.objects.all()
        return context
    
class hubList(ListView):
    model = hub
    context_object_name = 'list'
    template_name='list.html'
    paginate_by =2
class ProjectCategory(ListView):
    model = hub
    template_name='list.html'
    paginate_by = 1
    def get_queryset(self):
        self.category= self.kwargs['category']
        return hub.objects.filter(category= self.category)
    
    def get_context_data(self,**kwargs):
         context = super(ProjectCategory,self).get_context_data(**kwargs)
         context['catego'] = self.category
         return context
     
class ProjectLanguage(ListView):
    model = hub
    template_name='list.html'
    
    def get_queryset(self):
        self.language= self.kwargs['lang']
        return hub.objects.filter(language= self.language)
    
    def get_context_data(self,**kwargs):
         context = super(ProjectLanguage,self).get_context_data(**kwargs)
         context['language'] = self.language
         return context
        

hub/templates/detail.html

{% extends 'base.html' %}
{% load static %}
{% block body %}
<main class="content">
		<div class="single">

			<section class="trailer">
				<h3>Trailer</h3>
				<div class="trailer_frame">
					<iframe width="560" height="315" src="https://www.youtube.com/embed/x73-573aWfs" frameborder="0" allowfullscreen></iframe>
				</div>
			</section>
			<section class="movie">
				<img src="{{ detail.image.url }}">
				<ul>
					<li>{{detail}}</li>
					<li>{{detail.description}}.</li>
					<li><a href="genre.html">Adventure</a>, <a href="genre.html">Drama</a>, <a href="genre.html">Romance</a></li>
					<li><a href="cast.html">{{detail.cast}}</a>
					<li>{{detail.View_counts}} Views</li>
				</ul>
			</section>
			<section class="links">
				<h3>Links</h3>
				<ul class="dlinks">
					<li><a>Download</a></li>
					
					{% for link in link %}
						{% if link.type == 'D' %}
						<li><a href="{{link.link}}">Link {{forloop.counter}}</a></li>
						{% endif %}
					{% endfor %}
						
					
					
				</ul>
				<ul class="wlinks">
					<li><a>Watch</a></li>
				
					{% for link in link %}
						{% if link.type == 'W' %}
						<li><a href="{{link.link}}">Link {{forloop.counter}}</a></li>
						{% endif %}
					{% endfor %}
						
				</ul>
			</section>
			<section class="related">
				<h3>Related movies</h3>
				<div class="relatemovie">
					<a href="#"><img src="images/2.jpg"></a>
					<a href="#"><span class="relatedname">John Wick</span></a>
				</div>
				<div class="relatemovie">
					<a href="#"><img src="images/3.jpg"></a>
					<a href="#"><span class="relatedname">Spider Man Homecoming</span></a>
				</div>
				<div class="relatemovie">
					<a href="#"><img src="images/4.jpg"></a>
					<a href="#"><span class="relatedname">Beauty and Beast</span></a>
				</div>
				<div class="relatemovie">
					<a href="#"><img src="images/5.jpg"></a>
					<a href="#"><span class="relatedname">Pirates of the Caribbean: Dead Men Tell No Tales</span></a>
				</div>
				<div class="relatemovie">
					<a href="#"><img src="images/6.jpg"></a>
					<a href="#"><span class="relatedname">Fifty Shades Darker</span></a>
				</div>
				<div class="relatemovie">
					<a href="#"><img src="images/7.jpg"></a>
					<a href="#"><span class="relatedname">Transformers</span></a>
				</div>

			</section>

			<section class="comments">
				<h3>Comments</h3>
			</section>
		</div>
	</main>
{% endblock body %}
		

	

hub/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<main class="content">
		<section class="centered">
			{% if catego %}
			<h3>{{catego}}</h3>
			{% endif %}
			{% if language %}
			<h3>{{language}}</h3>
			{% endif %}
			<div class="movies">
					{% for projects in list  %}
				<div class="mov">
					<a href="single.html">
						<img src="{{projects.image.url}}">
						<h2 class="movietitle">{{projects.title}}</h2>
					</a>
				</div>
				{% empty %}
			<h3>SORRY WE ARE WORKING ON THIS</h3>
				{% endfor %}
			</div>
		{% if is_paginated %}
		<nav class="pagination">
			<ul>
				{% if page_obj.has_previous %}
				<li><a href="?page={{page_obj.previous_page_number}}">Prev</a></li>
				{% else %}
				<li class="disabled"></li>
				{% endif %}
				
				{% for page in page_obj.paginator.page_range  %}
					{% if page_obj.number == pages %}
					<li><a href="#">{{pages}}</a></li>
					{% else %}
					<li><a href="?page={{pages}}">{{page}}</a></li>
					{% endif %}
				{% endfor %}
				
				{% if page_obj.has_next %}
				<li><a href="?page={{page_obj.next_page_number}}">Next</a></li>
				{% else %}
				<li class="disabled"></li>
				{% endif %}
				
			</ul>
		</nav>
	</section>
	{% endif %}	
</main>
{% endblock body %}

		

hub/templates/single.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Space Between Us</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="css/swiper.min.css">
	<link rel="stylesheet" href="css/styles.css">

	<script src="js/jquery-3.1.1.min.js"></script>
	<script src="js/script.js"></script>


	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="index.html"><img src="img/logo.png" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="genre.html">Action</a></li>
							<li><a href="genre.html">Comedy</a></li>
							<li><a href="genre.html">Drama</a></li>
							<li><a href="genre.html">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							<li><a href="year.html">2017</a></li>
							<li><a href="year.html">2016</a></li>
							<li><a href="year.html">2015</a></li>
							<li><a href="year.html">2014</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="language.html">English</a></li>
							<li><a href="language.html">German</a></li>
						</ul>
					</li>
					<li><a href="mostwatched.html">Most Watched</a></li>
					<li class="mobsearch">
						<form class="mobform">
							<input type="text" name="s" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search">
				<input type="text" name="s" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="img/menu.svg"></div>
		</header>

		<main class="content">
			<div class="single">

				<section class="trailer">
					<h3>Trailer</h3>
					<div class="trailer_frame">
						<iframe width="560" height="315" src="https://www.youtube.com/embed/x73-573aWfs" frameborder="0" allowfullscreen></iframe>
					</div>
				</section>

				<section class="movie">
					<img src="images/9.jpg">
					<ul>
						<li>Space Between Us</li>
						<li>The first human born on Mars travels to Earth for the first time, experiencing the wonders of the planet through fresh eyes. He embarks on an adventure with a street smart girl to discover how he came to be.</li>
						<li><a href="genre.html">Adventure</a>, <a href="genre.html">Drama</a>, <a href="genre.html">Romance</a></li>
						<li><a href="cast.html">Gary Oldman</a>, <a href="cast.html">Asa Butterfield</a></li>
						<li>12,000 Views</li>
					</ul>
				</section>
				<section class="links">
					<h3>Links</h3>
					<ul class="dlinks">
						<li><a>Download</a></li>
						<li><a href="#">Link1</a></li>
						<li><a href="#">Link2</a></li>
						<li><a href="#">Link3</a></li>
					</ul>
					<ul class="wlinks">
						<li><a>Watch</a></li>
						<li><a href="#">Link1</a></li>
						<li><a href="#">Link2</a></li>
						<li><a href="#">Link3</a></li>
					</ul>
				</section>

				<section class="related">
					<h3>Related movies</h3>
					<div class="relatemovie">
						<a href="#"><img src="images/2.jpg"></a>
						<a href="#"><span class="relatedname">John Wick</span></a>
					</div>
					<div class="relatemovie">
						<a href="#"><img src="images/3.jpg"></a>
						<a href="#"><span class="relatedname">Spider Man Homecoming</span></a>
					</div>
					<div class="relatemovie">
						<a href="#"><img src="images/4.jpg"></a>
						<a href="#"><span class="relatedname">Beauty and Beast</span></a>
					</div>
					<div class="relatemovie">
						<a href="#"><img src="images/5.jpg"></a>
						<a href="#"><span class="relatedname">Pirates of the Caribbean: Dead Men Tell No Tales</span></a>
					</div>
					<div class="relatemovie">
						<a href="#"><img src="images/6.jpg"></a>
						<a href="#"><span class="relatedname">Fifty Shades Darker</span></a>
					</div>
					<div class="relatemovie">
						<a href="#"><img src="images/7.jpg"></a>
						<a href="#"><span class="relatedname">Transformers</span></a>
					</div>

				</section>

				<section class="comments">
					<h3>Comments</h3>
				</section>
			</div>
		</main>

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

	</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>


	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="index.html"><img src="{% static 'img/log.png' %}" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a>Category</a>
						<ul>
							<li><a href="{% url 'hub:Cate' 'W'%}">Web</a></li>
							<li><a href="genre.html">Comedy</a></li>
							<li><a href="genre.html">Drama</a></li>
							<li><a href="genre.html">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							<li><a href="year.html">2017</a></li>
							<li><a href="year.html">2016</a></li>
							<li><a href="year.html">2015</a></li>
							<li><a href="year.html">2014</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="{% url 'hub:Lan' 'PY'%}">Python</a></li>
							<li><a href="language.html">German</a></li>
						</ul>
					</li>
					<li><a href="mostwatched.html">Most Watched</a></li>
					<li class="mobsearch">
						<form class="mobform">
							<input type="text" name="s" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search">
				<input type="text" name="s" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster1.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster2.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>
{% block body %}
  
{% endblock body %}
		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		<!-- Swiper JS -->
		<script src="js/swiper.min.js"></script>

		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function(){


				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

			
		</script>


	</div>
</body>
</html>

templates/bs.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="css/swiper.min.css">
	<link rel="stylesheet" href="css/styles.css">

	<script src="js/jquery-3.1.1.min.js"></script>
	<script src="js/script.js"></script>


	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="index.html"><img src="img/logo.png" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="genre.html">Action</a></li>
							<li><a href="genre.html">Comedy</a></li>
							<li><a href="genre.html">Drama</a></li>
							<li><a href="genre.html">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							<li><a href="year.html">2017</a></li>
							<li><a href="year.html">2016</a></li>
							<li><a href="year.html">2015</a></li>
							<li><a href="year.html">2014</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="language.html">English</a></li>
							<li><a href="language.html">German</a></li>
						</ul>
					</li>
					<li><a href="mostwatched.html">Most Watched</a></li>
					<li class="mobsearch">
						<form class="mobform">
							<input type="text" name="s" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search">
				<input type="text" name="s" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="img/menu.svg"></div>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="images/slider/poster2.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster1.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster2.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>
        {% block body %}
              
        {% endblock body %}

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		<!-- Swiper JS -->
		<script src="js/swiper.min.js"></script>

		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function(){


				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

			
		</script>


	</div>
</body>
</html>